#!/bin/sh

# We gotta add a `.readme` field to each cargo toml file. Hard to automate
# so we automate editing the files & saving it.

dirname="$(dirname "$(readlink -f "$0")")"

dirs="$dirname/../../*"
for f in $dirs; do
  pushd "$f" > /dev/null
    if [ -f Cargo.toml ]; then
      count="$(grep readme < Cargo.toml | wc -c)"
      if [ $count = 0 ]; then
        vim Cargo.toml
        git add -A
        git commit -am 'Add .readme field to Cargo.toml'
        cpv patch
      fi
    fi
  popd > /dev/null
done
